enum ResourceTypes {
  FETCH_RESOURCE = 'FETCH_RESOURCE',
  RESOURCE_ERROR = 'RESOURCE_ERROR',
  RESOURCE_SUCCESS = 'RESOURCE_SUCCESS',
  RESET_RESOURCE = 'RESET_RESOURCE',
}

export default ResourceTypes
