enum ResourceTypes {
  FETCH_RESOURCE = 'FETCH_RESOURCE',
  RESOURCE_ERROR = 'RESOURCE_ERROR',
  RESOURCE_SUCCESS = 'RESOURCE_SUCCESS',
  RESOURCE_UPDATE = 'RESOURCE_UPDATE',
  RESET_RESOURCE = 'RESET_RESOURCE',
  NEW_ORDER = 'NEW_ORDER',
  CANCEL_UPDATE = 'CANCEL_UPDATE',
}

export default ResourceTypes
