enum XBTUSD_GROUPS_ENUM {
  small = 0.5,
  medium = 1,
  large = 2.5,
}

enum ETHUSD_GROUPS_ENUM {
  small = 0.05,
  medium = 0.1,
  large = 0.25,
}

const XBTUSD_GROUPS = [XBTUSD_GROUPS_ENUM.small, XBTUSD_GROUPS_ENUM.medium, XBTUSD_GROUPS_ENUM.large]
const ETHUSD_GROUPS = [ETHUSD_GROUPS_ENUM.small, ETHUSD_GROUPS_ENUM.medium, ETHUSD_GROUPS_ENUM.large]

export { XBTUSD_GROUPS, XBTUSD_GROUPS_ENUM, ETHUSD_GROUPS, ETHUSD_GROUPS_ENUM }
